version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "communication"
      MONGO_INITDB_ROOT_PASSWORD: "communication-2023"

  redis-master:
    container_name: redis-master
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_REPLICATION_MODE: "master"
      REDIS_PASSWORD: "communication-2023"

  redis-slave:
    image: bitnami/redis:latest
    environment:
      REDIS_REPLICATION_MODE: "slave"
      REDIS_PASSWORD: "communication-2023"
      REDIS_MASTER_HOST: "redis-master"
      REDIS_MASTER_PORT: "6379"
      REDIS_MASTER_PASSWORD: "communication-2023"
    deploy:
      replicas: 2

  redis-sentinel:
    container_name: redis-sentinel
    image: bitnami/redis-sentinel:latest
    ports:
      - "26379:26379"
    environment:
      REDIS_MASTER_SET: "redis"
      REDIS_MASTER_HOST: "redis-master"
      REDIS_MASTER_PASSWORD: "communication-2023"
    depends_on:
      - redis-master
      - redis-slave

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "communication"
      RABBITMQ_DEFAULT_PASS: "communication-2023"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit channel_max 8092"

  message:
    container_name: message
    image: message:latest
    build:
      context: ./
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      MESSAGE_SERVER_NAME: "Message"

      MESSAGE_QUEUE_HOST: "rabbitmq"
      MESSAGE_QUEUE_PORT: "5672"
      MESSAGE_QUEUE_USERNAME: "communication"
      MESSAGE_QUEUE_PASSWORD: "communication-2023"

      MESSAGE_DATABASE_HOST: "mongodb"
      MESSAGE_DATABASE_PORT: "27017"
      MESSAGE_DATABASE_USERNAME: "communication"
      MESSAGE_DATABASE_PASSWORD: "communication-2023"

      MESSAGE_CACHE_MASTER_SET: "redis"
      MESSAGE_CACHE_MASTER_PASSWORD: "communication-2023"
      MESSAGE_CACHE_SENTINEL_HOST: "redis-sentinel"
      MESSAGE_CACHE_SENTINEL_PORT: "26379"
      MESSAGE_CACHE_SENTINEL_PASSWORD: "communication-2023"
    volumes:
      - "/Users/ling/Documents/personal-working/message:/app"
    tty: true
    depends_on:
      - redis-master
      - redis-slave
      - redis-sentinel
      # - rabbitmq
      - mongodb
