[tool.poetry]
name = "message"
version = "0.1.0"
description = "a general message notification system"
authors = ["lingfromSh <541023490@qq.com>"]
license = "AGPL V3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sanic = "^23.3.0"
tortoise-orm = "^0.19.3"
pydantic = "^2.0.2"
graphene = "^3.2.2"
motor = "^3.2.0"
aio-pika = "^9.1.4"
grpcio = "^1.56.0"
redis = "^4.6.0"
orjson = "^3.9.2"
environ-config = "^23.2.0"
aiohttp = "^3.8.4"
python-ulid = "^1.1.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
black = "^23.7.0"
isort = "^5.12.0"
flake8 = "^6.0.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"


[[tool.poetry.source]]
name = "sjtu"
url = "https://mirror.sjtu.edu.cn/pypi/web/simple"
priority = "default"

[tool.isort]
profile = "black"
force_single_line = true
group_by_package = true
skip = [".gitignore", ".dockerignore"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
