persistence:
  dsn: postgres://pgadmin:pgpassword@pgbouncer:6432/message

cache:
  dsn: redis://redis:6379/

queue:
  dsn: amqp://rbadmin:rbpassword@rabbitmq:5672/
  prefecth_count: 100

storage:
  mode: local
  options:
