persistence:
  dsn: postgres://pgadmin:pgpassword@localhost:6432/message

cache:
  dsn: redis://localhost:6379/

queue:
  dsn: amqp://rbadmin:rbpassword@localhost:5672/
  prefecth_count: 100

storage:
  mode: local
  options:
