services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    profiles:
      - "standalone"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    restart: always
    profiles:
      - "standalone"

  pgbouncer:
    container_name: pgbouncer
    image: bitnami/pgbouncer:latest
    ports:
      - "6432:6432"
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - PGBOUNCER_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_HOST=postgres
    profiles:
      - "standalone"
